[package]
name = "dxf_viewer_masonry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
tracing-tracy = ["dep:tracing-tracy", "dep:tracy-client"]
tracing-tracy-memory = ["tracing-tracy"]

[dependencies]
accesskit = "0.19.0"
anyhow = "1"
joto_constants = "0.1.1"
masonry = { path = "/home/aaron/src/xilem/masonry"}
masonry_winit = { path = "/home/aaron/src/xilem/masonry_winit"}
smallvec = "1.15"
tracing-subscriber.workspace = true
tracing.workspace = true
tracing-tracy = { workspace = true, optional = true }
tracy-client = { workspace = true, optional = true }
winit = "0.30.10"

static_aabb2d_index = { version = "2.0.0", features = ["unsafe_optimizations"] }

tabulon = { workspace = true, features = ["std"] }
tabulon_dxf = { workspace = true }
tabulon_vello = { workspace = true }

[lints]
workspace = true
